version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
      args:
        - project=${PROJECT}
        - package=${PACKAGE}

    volumes:
       - ./config:/${PROJECT}/config:ro
       - ./${PACKAGE}:/${PROJECT}/${PACKAGE}:ro
       - ./static:/static:ro
       - ./start.py:/${PROJECT}/start.py

    command:
      python start.py
