version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        - project=${PROJECT}
        - package=${PACKAGE}

    volumes:
      - ./$PACKAGE:/${PROJECT}/${PACKAGE}:ro
      - ./test:/${PROJECT}/test
      - ./artifacts:/${PROJECT}/artifacts
      - ./source:/source

    command:
      py.test --cov=$PACKAGE  -vv --cov-report html:artifacts/html-coverage --cov-report term --html=artifacts/html-report/report.html /$PROJECT/test