version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web

    volumes:
       - /etc/localtime:/etc/localtime:ro
       - ./config:/${PROJECT}/config:ro
       - ./${PACKAGE}:/${PROJECT}/${PACKAGE}:ro
       - ./static:/static:ro
       - ./start.py:/${PROJECT}/start.py

    command:
      python start.py
